port: 9595
ip: localhost
storagePath: ./.cdn-cache
registry:
  url: 'http://registry.npmjs.org/'
accounts:
  zkochan:
    registry:
      url: 'http://registry.npmjs.org/'
mongodb:
  address: localhost
  port: 27017
  name: sitegate-registry-dev
maxAge:
  js: 4h
  css: 4h
  jpg: 4h
  default: 4h
