port: 9595
ip: localhost
storagePath: ./.cdn-cache
registry:
  url: 'https://registry.npmjs.org/'
accounts:
  zkochan:
    registry:
      url: 'http://registry.npmjs.org/'
maxAge:
  js: 4h
  css: 4h
  jpg: 4h
  default: 4h
