port: 9595
ip: localhost
origin: 'cdn.foso.me'
storagePath: ./.cdn-cache
registry:
  url: 'http://registry.npmjs.org/'
mongodb:
  name: sitegate-registry
maxAge:
  js: 4h
  css: 4h
  jpg: 4h
  default: 4h
