port: 9595
ip: localhost
storagePath: ./files
registry: 'http://registry.npmjs.org/'
accounts:
  zkochan:
    registry: 'http://registry.npmjs.org/'
maxAge:
  js: 4h
  css: 4h
  jpg: 4h
  default: 4h
